### ISSUE TITLE
Bug: rerunning friends production command

### ISSUE THREAD

**Issue by nshadskiy** [KIT-CMS/KingMaker#31]
I'm using the `nmssm_devs` branches of CROWN and CROWN-TauAnalysis and the `main` branch of KingMaker.

During the run of ntuple production and afterwards first run of friend production everything is fine. Example commands are:
```bash
law run ProduceSamples --analysis tau --config nmssm_config --sample-list nmssm_samples.txt --shifts None --production-tag 01_2024_nmssm_nominal_v5 --workers 40 --scopes mt,tt
```
and for friends
```bash
law run ProduceFriends --analysis tau --config nmssm_config --friend-config nmssm_fake_factors --sample-list nmssm_samples.txt --shifts None --friend-name fake_factors_v1 --production-tag 01_2024_nmssm_nominal_v5 --workers 40 --scopes mt,tt
```

The bug occurs if I try to run the same `ProduceFriends` command again. I'm certain that all job finished successfully and produced the friend root files. So the expectation would be in the second run nothing should happen.
But for each sample one single job is always resubmitted. Example for a diboson sample
```bash
15:55:17: all: 8, pending: 0 (+0), running: 0 (+0), finished: 7 (+7), retry: 1 (+1), failed: 0 (+0) - WW_TuneCP5_13TeV-pythia8_RunIISummer20UL18NanoAODv9-106X (Analysis: tau FriendConfig: nmssm_fake_factors Tag: 01_2024_nmssm_nominal_v5)
1 failed job(s) in task CROWNFriends_KingMaker____tau_3bc4820171:
    job: 2, branches: [1], id: dummy_job_id, status: retry, code: 0, error: unknown job id, log: None
```
It's not dependent on the number of all jobs for a sample, but I found that if I process friends for only one channel this is not happening and with 3 channel ("et","mt","tt") always 2 jobs are resubmitted.

**Comment by harrypuuter** [comment]
Fixed with #32
