### ISSUE TITLE
Update xrootd when new version is available

### ISSUE THREAD

**Issue by harrypuuter** [KIT-CMS/KingMaker#4]
As soon as 5.4.3 is available, update gfal and xrootd 

(includes then https://github.com/xrootd/xrootd/issues/1673)

**Comment by tvoigtlaender** [comment]
The new version seems to be out and available through conda. 
So this issue could now be resolved if it is still relevant.

**Comment by tvoigtlaender** [comment]
updated as part of https://github.com/KIT-CMS/KingMaker/pull/45
