### ISSUE TITLE
Symlinks not parseable correctly

### ISSUE THREAD

**Issue by jhvoss** [KIT-CMS/KingMaker#53]
For a mounted file e.g. on the /afs to /eos , sourcing Kingmaker setup does not use the symlink path correctly and looks for it on /afs instead /eos :
```bash
myeos -> /eos/user/e/example/myeos/ 
```

```bash
$ source setup.sh Kingmaker myeos
```
It then tries to install into `/afs/cern.ch/user/e/example/KingMaker/myeos/miniforge` and not the /eos path.

**Comment by tvoigtlaender** [comment]
Fixed in https://github.com/KIT-CMS/KingMaker/pull/54
